language: objective-c
xcode_project: objc4-756.2/objc4-756.2/objc.xcodeproj
xcode_scheme: objc
osx_image: xcode10.1

script:
- set -o pipefail
- xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=My Mac" -enableCodeCoverage YES | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
